spring:
    # datasource:
    #     url: jdbc:postgresql://localhost:5432/
    #     username: admin
    #     password: admin1234
    #     driver-class-name: org.postgresql.Driver
    flyway:
        enabled: false
    # jpa:
    #     show-sql: true
    #     properties:
    #         hibernate:
    #             dialect: org.hibernate.dialect.PostgreSQLDialect
application:
    db:
        tenant:
            locations: db/migration/tenant
        master:
            locations: db/migration/master
    jwt:
        secret: 51a0ab47b8037e2b635a280b409480ed
        expiration: 600000000
server:
    error:
        whitelabel:
            enabled: true
